version: '2.3'

services:
  rentacar_db:
    image: bitnami/postgresql
    container_name: database_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentacar
      - POSTGRES_DB=rentacar

